### ISSUE TITLE
Turn into a Forge Mod

### ISSUE THREAD

**Issue by me4502** [Thinkofname/vanillacord#3]
This could quite easily become a forge mod, allowing for Forge servers to support IP Forwarding.

**Comment by Thinkofname** [comment]
I know nothing about the forge system as I've never made a forge mod, mix that with the changes forge did in 1.8 (`\0FML\0`) I don't think this is possible for now unless both sides work together to reach a solution.

**Comment by me4502** [comment]
I'm trying to make this into a forge mod atm, I'll see how it works

**Comment by Thinkofname** [comment]
Well with the latest bungee its going to have issues https://github.com/SpigotMC/BungeeCord/commit/4809f1f80ace9ae87b91453c8887c70f5e098bd0 Either you get the ipforwarding or the `\0FML\0` part depending on your config, not both like i assume your mod would need
